server:
  port: 8092
spring:
  application:
    name: favourite-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/PlayerFavDB}
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-address: localhost:9092
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka