git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/vlabs/faqs.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/tollgate-practice/boilerplate/angular-practice-assessment-1-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstatewave-1/react_docker_example.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/hcl-wave-1-demo/swagger-demo.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/naik.ullas/sba_players_app.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstatewave-1/sba_players_app.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/naik.ullas/newz-step6-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_newz/newz-step6-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/hcl-wave-1-demo/kafka-dockerization-demo.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstate_demo/eureka-zuul-docker-compose-demo.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_keep_v2/keepnote-step7-kafka-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstatewave-1/sba_players_app.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstatewave-1/sba_muzic_app.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstatewave-1/sba_gipher_application.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstatewave-1/sba_matchtracking_app.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstatewave-1/java_docker_mysql.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstatewave-1/java_docker_basic.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/naik.ullas/newz-step5-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_newz/newz-step5-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/hcl-wave-1-demo/kubernetes-example-2.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/naik.ullas/newz-step4-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_newz/newz-step4-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstate_demo/kafka-integration-demo-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstate_demo/kafka-integration_demo.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstate_demo/jwt-example.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/ghouse/iqvia_demos.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/Amisha.Gupta/check.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_pgp/foundation_project_football_league_boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/Amisha.Gupta/gitlab_ci_cd_test.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/hcl-wave-1-demo/kafka-integration-demo.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/pgp_wave1_class_demo/iteration-example.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/pgp_wave1_class_demo/conversion-between-array-and-collection.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/pgp_wave1_class_demo/comparable-comparator-example.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/pgp_wave1_class_demo/arraylistexample.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/pgp_wave1_class_demo/collections-set-example.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/pgp_wave1_class_demo/collections-map-example.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_pgp/challenge-43-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_pgp/challenge-42-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_pgp/challenge-41-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_pgp/challenge-40-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/banking/AnlyticsForDecisionMaking.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/banking/BlockChainResearch.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/banking/Transforming-a-bank-b-becoming-digital-to-the-core.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstate_demo/eureka-zuul-configservice-demo.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/banking/Four-Use-Cases-Predictive-Analytics-in-Banking.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/banking/Business-Analytics-Everything-You-Need-to-Know.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstate_demo/spring-boot-aop-demo.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/shankar.r/mockito_demo_code.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/shankar.r/practice-exercise-junit-testing.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstatewave-1/java_spring_boot_restcontroller.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstatewave-1/java_springboot_simanta.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/naik.ullas/newz-step3-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_newz/newz-step3-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstatewave-1/springboot_jpa_book.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/hcl-wave-1-demo/eureka_zuul_configserver_demo.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/Dhinesh.Kumar/sa_flight_booking.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_keep/KeepNote-Step6-Boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/pgp_wave1_class_demo/binary-search-tree.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_pgp/challenge-39-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/shankar.r/practice-exercise-mysql.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/shankar.r/practice-exercise-rdbms.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/pgp_wave1_class_demo/linked-binary-tree.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstatewave-1/java_ex1.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/hcl-wave-1-demo/dockerization-demo.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_pgp/challenge-38-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/hcl-wave-1-demo/docker-compose-demo.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/pgp_wave1_class_demo/queue-using-linked-list.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/pgp_wave1_class_demo/stack-using-linked-list.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_pgp/challenge-37-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstate_demo/hibernate-example.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstate_demo/spring-mvc-userapp.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/naik.ullas/newz-step2-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_newz/newz-step2-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/brillio_java_fsd/spring-angular-integration.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/brillio_java_fsd/jwtfilter.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/mg_rbs_wave1/microservices.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_pgp/challenge-35-part-2-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/ravi.chandran/array-exercise.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/mg_rbs_wave1/docker.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/brillio_java_fsd/docker_swagger_ex.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstatewave-1/java_springboot_jpa.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/brillio_java_fsd/microservices_ex.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/pgp_wave1_class_demo/challenge-36-explanation.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/brillio_java_fsd/springboot_mysql.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstatewave-1/java_sringboot_demo.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/brillio_java_fsd/spring_aop.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_pgp/challenge-36-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/hcl-wave-1-demo/jwt-example.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/pgp_wave1_class_demo/doubly-linked-list.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/brillio_java_fsd/restservice.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/hcl-wave-1-demo/spring-boot-mongodb.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstatewave-1/java_spring_orm.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstatewave-1/java_spring_jdbc.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/naik.ullas/newz-step1-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_newz/newz-step1-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/mg_rbs_wave1/ramdomdocs.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/brillio_java_fsd/spring_hibernate_integration.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/pgp_wave1_class_demo/challenge-27-class-structure.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/pgp_wave1_class_demo/singly-linked-list.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstatewave-1/java_spring_mvc.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/brillio_java_fsd/hibernate_ex.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_pgp/challenge-35-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/brillio_java_fsd/spring_mvc.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/pgp_wave1_class_demo/searching-algorithms.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/stack_java_pgp/challenge-34-boilerplate.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstatewave-1/java_spring_annotation.git
git clone https://oauth2:cvUZdYC_fMC3_cxkL5HT@gitlab.stackroute.in/allstatewave-1/java_spring_core_with_xml.git
