eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      
spring:
 application:
    name: newz-nexflix-zuul-api-gateway
server:
  port: 8091 
zuul:
  host:
    connect-time-millis: 60000
  routes:
    news:
      serviceId: NewsService
    newsSource:
      serviceId: NewsSourceService
    authentication:
      serviceId: AuthenticationService
