server:
  port: 8092
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/fitnesszone_db}
  kafka:
    bootstrap-address: ${KAFKA_URL:localhost:9092}
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: ${EUREKA_ADDRESS:http://localhost:8761/eureka}