version: '3.5'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    network_mode: host
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: fitness_zone
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysql" ,"-u", "root", "-ppassword" ]
      timeout: 20s
      retries: 10

  mongo:
    image: mongo:latest
    container_name: mongo_container
    network_mode: host
    ports:
      - 27017:27017

  apigateway:
    image: apigateway:1.0
    build: ./ApiGateway
    container_name: apigateway_container
    network_mode: host
    ports:
    - 9000:9000
    environment:
      API_GATEWAY_PORT: 9000
      EUREKA_SERVER_IP: localhost
      EUREKA_SERVER_PORT: 8761
    restart: always
    depends_on:
      - eurekaservice

  eurekaservice:
    image: eurekaservice:1.0
    build: ./EurekaService
    container_name: eurekaservice_container
    network_mode: host
    ports:
    - 8761:8761
    restart: always
    environment:
      EUREKA_SERVER_PORT: 8761

  userservice:
    image: userservice:1.0
    build: ./UserService
    container_name: userservice_container
    network_mode: host
    ports:
      - 8095:8095
    environment:
      MYSQL_URL: jdbc:mysql://localhost:3306/fitness_zone
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      EUREKA_SERVER_IP: localhost
      EUREKA_SERVER_PORT: 8761
    depends_on:
      - mysql
      - eurekaservice
      - apigateway
    restart: always

  productservice:
    image: productservice:1.0
    build: ./ProductService
    container_name: productservice_container
    network_mode: host
    ports:
      - 8093:8093
    environment:
      MONGO_URI: mongodb://localhost:27017/productdb
      EUREKA_SERVER_IP: localhost
      EUREKA_SERVER_PORT: 8761
    depends_on:
      - mongo
      - eurekaservice
      - apigateway
    restart: always

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    network_mode: host
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    network_mode: host
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
