spring:
 application: 
  name: NewsSourceService
 data:
   mongodb:
#     username: ${MONGO_USER}
#     password: ${MONGO_PASSWORD}
#     database: ${MONGO_DATABASE}
#     port: ${MONGO_PORT}
#     host: ${MONGO_HOST}
     username: admin
     password: admin
     database: admin
     port: "27017"
     host: "127.0.0.1"
server:
 port: 8083
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka