server:
  port: 8092
spring:
  application:
    name: enquiry-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/fitnesszone_db}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka