apiVersion: v1
kind: ConfigMap
metadata:
  name: config-data
data:
  mysql_database: "userdb"
  mysql_url: "jdbc:mysql://mysql:3306/userdb"
  gymservice_mongo_uri: "mongodb://mongo:27017/fitnesszone_productdb"

