server:
  port: 8091
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/fitnesszone_db}
#eureka:
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: ${EUREKA_ADDRESS:http://localhost:8761/eureka}