server:
  port: 8093
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/fitnesszone_db}
  kafka:
    bootstrap-address: localhost:9092
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka